train:
  imgs: 'data/train_imgs/'    #
  mpms: 'data/train_mpms/'    #
  itvs: [1]                   # Multiple patterns are OK like [1, 3, 5, 7, 9]
  scale: 1.0                  # Image scaling factor
  epochs: 10                  # Number of epoch
  batch_size: 1               # Batch size
  lr: 0.0001                  # Learning rate of Adam

eval:
  imgs: 'data/eval_imgs/'     # None is OK. In that case, eval.rate in the training data is used for evaluation.
  mpms: 'data/eval_mpms/'     # None is OK
  itvs: [1]                   # Multiple patterns are OK like [1, 3, 5, 7, 9]
  scale: 1.0                  # Image scaling factor
  rate: 0.2                   # Evaluation rate for no eval data

output:
  save: True
  dir: 'checkpoints/'

load: False                   # If you use a trained model, please rewrite it.

dataloader:
  edge: 10                    # Image edge range (This area will not be cropped)
  height: 256                 # Number of pixel of crop height
  width: 256                  # Numper of pixel of crop width
