# Hydra configuration file for training

train:
  imgs: 'cell_data/train_imgs/'    #
  mpms: 'cell_data/train_mpms/'    #
  itvs: [1]                   # Multiple patterns are OK like [1, 3, 5, 7, 9]
  epochs: 200                 # Number of epoch
  batch_size: 8               # Batch size
  lr: 0.0001                  # Learning rate of Adam

eval:
  imgs: 'cell_data/eval_imgs/'     # None is OK. In that case, eval.rate in the training data is used for evaluation.
  mpms: 'cell_data/eval_mpms/'     # None is OK
  itvs: [9]                   # Multiple patterns are OK like [1, 3, 5, 7, 9]
  rate: 0.2                   # Evaluation rate for no eval data

output:
  save: True
  dir: 'checkpoints/'

load: False                   # If you use a trained model, please rewrite it.

dataloader:
  edge: 10                    # Image edge range (This area will not be cropped)
  height: 256                 # Number of pixel of crop height
  width: 256                  # Number of pixel of crop width

info:
  direction: peak         # Direction type of MPM
