# Hydra configuration file for ground-truth generation

file:
  tracklet: 'cell_data/DIC_C2DH_HELA_01.txt'                     # [frame id x y parent_id(-1 if none)]
  target: 'cell_data/train_imgs/DIC_C2DH_HELA_01/0000.tif'       # One of the target images

path:
  save_path: 'cell_data/train_mpms/DIC_C2DH_HELA_01/'            # Create directory for each interval

param:
  z_value: 5                                    # z-axis unit (pixel)
  sigma: 6                                      # sigma of gaussian filter
  itvs: [1]                                     # MPM intervals (list), e.g. [1], [3, 5], [1, 2, 3], ...

#direction: 'parallel'
direction: 'peak'
